---

- include: "php_modules/install/packages.yml"
  tags: [php-modules, install, packages]

- include: "php_modules/get/sapis/available.yml"
  tags: [php-modules, get, sapis, available]

- include: "php_modules/get/modules/available.yml"
  tags: [php-modules, get, modules, available]

- include: "php_modules/get/module/status.yml"
  tags: [php-modules, get, modules, enabled]

- include: "php_modules/get/modules/enabled.yml"
  tags: [php-modules, get, modules, enabled]

- include: "php_modules/get/modules/disabled.yml"
  tags: [php-modules, get, modules, enabled]

- include: "php_modules/get/modules/to_enable.yml"
  tags: [php-modules, get, modules, to-enable]

- include: "php_modules/get/modules/to_disable.yml"
  tags: [php-modules, get, modules, to-disable]

- include: "php_modules/enable/modules.yml"
  tags: [php-modules, enable, modules]

- include: "php_modules/disable/modules.yml"
  tags: [php-modules, disable, modules]

- include: "php_modules/notify/services.yml"
  tags: [php-modules, notify, services]

